<?php

    // $dbtable_from_type = array(
    //     "soccer" => "",
    //     "baseball" => "",
    //     "basketball" => "",
    //     "volleyball" => "",
    //     "hockey" => ""
    // );

    $dbtable_from_type = array(
    "best" => "community",
    "free" => "community",
    "humor" => "community",
    "photo" => "community",
    "food" => "community",
    "poker" => "community",
    "notice" => "notice",
    "mov" => "school",
    "book" => "school",
    "cafe" => "offline",
    "pokerroom" => "offline",
    "tournament" => "offline",
    "event" => "event",
    "grinding" => "grinding"
);

    $thumb_size = array(
        "mini" => array(100, 75),
        "photo" => array(225, 180),
        "main" => array(720, 400)
    );


?>
